[project]
name = "chatbot-embedding-tools"
version = "0.1.0"
description = "A Flask-based chat interface"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
